{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coworker-client.fullname" . }}-backend-secret
  labels:
    {{- include "coworker-client.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "backend.db.password is required" .Values.backend.db.password | quote }}
  RABBITMQ_PASSWORD: {{ required "backend.rabbitmq.password is required" .Values.backend.rabbitmq.password | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ required "backend.keycloak.adminPassword is required" .Values.backend.keycloak.adminPassword | quote }}
  COWORKER_SERVER_PASSWORD: {{ required "backend.coworkerServer.password is required" .Values.backend.coworkerServer.password | quote }}
{{- end }}
